service: serverless-typescript-template
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs22.x
  region: ${param:region}
  environment:
    STAGE: ${param:stage}
    REGION: ${param:region}

plugins:
  - serverless-offline

package:
  exclude:
    - .github
    - .serverless
    - coverage
    - src
    - test
    - .gitignore
    - eslint.config.js
    - jest.config.js
    - LICENSE
    - README.md
    - serverless.yml
    - serverless.offline.yml
    - tsconfig.json

functions:
  get-users:
    handler: dist/handlers/get-users-http.handler
    events:
      - http:
          path: /v1/users
          method: get
