service: serverless-typescript-template
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    STAGE: ${param:stage}
    REGION: us-east-1

plugins:
  - serverless-offline

package:
  exclude:
    - src/**/*.ts

functions:
  get-users:
    handler: src/handlers/get-users.handler
    events:
      - http:
          path: get-users
          method: get