export abstract class MessageCodes {
  static OPERATION_SUCCESSFUL = 'OPERATION_SUCCESSFUL'
  static RESOURCE_CREATED = 'RESOURCE_CREATED'
  static BAD_REQUEST = 'BAD_REQUEST'
  static NOT_FOUND = 'NOT_FOUND'
  static UNCONTROLLER_ERROR = 'UNCONTROLLER_ERROR'
  static SERVICE_NOT_AVAILABLE = 'SERVICE_NOT_AVAILABLE'
}